### PR TITLE
Change LENGTH_STEP to 5 minutes

### PR DESCRIPTION
**Pull request by genehack**
See recent email from VMB to SRE list about inability to have 20 and
50 minute talks.

I _think_ this will resolve that issue. Standard disclaimers apply: no
tests and I'm not totally sure what I'm doing in this codebase just
yet 8^)

### CODE REVIEW

**Comment by genehack** [comment]
@vmbrasseur you'll probably want to be a watcher on this conversation too...

**Comment by differentreality** [comment]
This was introduced as a feature in https://github.com/openSUSE/osem/pull/1319, in case you are interested in updating (Note though, that currently GSoC is on and our master is being constantly updated).

**Comment by differentreality** [comment]
And so is your commit fd652cf7f7a979483e9ae6fe28ca80b78c004c55

screenshot from 2017-06-16 11-01-24
screenshot from 2017-06-16 11-01-45

**Comment by vmbrasseur** [comment]
Greetings, all. We really need to get the CFP live ASAP. Any chance of a resolution on this PR and an update of the SeaGL OSEM installation?

**Comment by kormoc** [comment]
@vmbrasseur - I've completed the sync from upstream, which will allow us to use their code. I'll be deploying that code shortly.

**Pull request closed without merging**
