### PR TITLE
Add proposal fields

### PR DESCRIPTION
**Pull request by genehack**
We'd like to add these two fields to the proposal field for the 2018 CFP. I _think_ this PR should be sufficient for that. 

We also need to be able to _see_ this data when reviewing talk proposals. I'm not entirely sure where those modifications need to be made. I'm also not sure what level of testing is considered appropriate in this project for this type of change. 

Additionally, @vmbrasseur mentioned also adding an aggregate measure of both of these to the dashboard, so that we can have some ongoing feedback on the how we'd doing on both fronts.

Finally, our current timeframe for opening the CFP is June 19th (i.e., next Monday). **Ideally** we will be able to get these changes completed by then, if at all possible?

### CODE REVIEW

**Comment by meonkeys** [comment]
@shanet please say ASAP whether you're able to review this or if we should find someone else, thanks! (like maybe @altsalt or @kormoc ... )

@differentreality, is this something you'd accept upstream?

**Comment by differentreality** [comment]
While I find the fields useful, I don't think they necessarily belong to the proposal. 

Code looks good for the proposal form, and I am happy to provide you with a PR to show that information on the admin side as well (probably during the weekend). But I would not merge this upstream as it is.

I do encourage you to open an issue for it though, so that we can think where it's best to put those fields, so that we can get the information.
My first thought is that the diversity checkbox is a user field (which may, or may not be visible in the proposal form). But I'd like to give it some more thought - and maybe others have more ideas about it.

**Comment by differentreality** [comment]
So with the changes of this PR, the form would look like this: 

screenshot from 2017-06-15 11-28-48

**Comment by genehack** [comment]
As far as where the proper place is in the data model to store this information, I don't have a *super* strong opinion on that, but I can easily imagine situations where somebody might want to tick one of those boxes for one talk, but not another -- particularly the 'diversity' one. (E.g., somebody might submit two talks, one technical and one more community/cultural, about being a member of a historically under-represented group. They might want to tick the box for the latter, but not for the former (some members of these groups actively avoid identifying as members of those groups because they want to be evaluated strictly on the merits of the proposal and not on extraneous factors.))

The other complication is if you set the 'first_time' flag on the user profile, it's going to need to be reset at some point (if the person gets a talk accepted), so that will need to be tracked and handled.

**Comment by vmbrasseur** [comment]
Greetings, all. We really need to get the CFP live ASAP. Any chance of a resolution on this PR and an update of the SeaGL OSEM installation?

**Pull request merged**
